### PR TITLE
NEW MAJOR VERSION - added large file support and upload progress.

### PR DESCRIPTION
**Pull request by IvanKalinin**
switched form node-request to promise based library 'axios';
added methods for large files;
added on download and on upload options;
updated tests

### CODE REVIEW

**Comment by crazyscience** [comment]
@yakovkhalinsky Hold on for a bit before you merge this one in.

**Comment by crazyscience** [comment]
@yakovkhalinsky Need to update the Readme and probably bring you up to speed with the changes.

**Comment by yakovkhalinsky** [comment]
Excellent! Very much appreciate this massive contribution.

**Comment by crazyscience** [comment]
@yakovkhalinsky Looks good to me. Note change in version number to v1.0.0. `Readme.md` contains relevant upgrade instructions to quell any developer tears. Assuming people are using proper versioning constraints (which they probably aren't), there shouldn't be any issues.

**Comment by crazyscience** [comment]
Closed for further testing and verification. New PR will be available after extensive testing, both unit and human.

**Comment by crazyscience** [comment]
Needs to include `q` in package.json.

**Comment by crazyscience** [comment]
@yakovkhalinsky ok. ready to go.

**Comment by yakovkhalinsky** [comment]
Very nice work mate 👍 

Merging

**Comment by yakovkhalinsky** [comment]
Will npm publish when I get home in ~5 hours :)

**Pull request merged**
