### PR TITLE
Fixed binary files

### PR DESCRIPTION
**Pull request by legacy3**
TLDR: https://stackoverflow.com/questions/14855015/getting-binary-content-in-node-js-using-request

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
Thanks for the PR @legacy3 

Will merge it after the tests have pass and publish it to NPM later today :dart:

**Comment by yakovkhalinsky** [comment]
@legacy3 looks like the expectation of one of the unit tests needs to be updated.

If you can could you please update the test? otherwise I'm happy to do it when I get time later today.
```
  1) actions/file downloadFileByName with good response should set correct options and resolve with good response (filename to be encoded):
      Error: expected { url: 'https://download/file/unicornBox/unicorns-and_rainbows!%40%23%24%25%5E%26.png',
  headers: { Authorization: 'unicorns and rainbows' },
  encoding: null } to sort of equal { url: 'https://download/file/unicornBox/unicorns-and_rainbows!%40%23%24%25%5E%26.png',
  headers: { Authorization: 'unicorns and rainbows' } }
      + expected - actual
       {
      -  "encoding": [null]
         "headers": {
           "Authorization": "unicorns and rainbows"
         }
         "url": "https://download/file/unicornBox/unicorns-and_rainbows!%40%23%24%25%5E%26.png"
      
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.eql (node_modules/expect.js/index.js:230:10)
      at Context.<anonymous> (test/unit/lib/actions/fileTest.js:366:43)
      at test/unit/lib/actions/fileTest.js:361:21
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:556:49
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
```

**Comment by yakovkhalinsky** [comment]
@legacy3 I'm going to rebase your code onto master and then fix the test :+1:

**Comment by yakovkhalinsky** [comment]
All good test is fix thanks again for the PR @legacy3 :+1:

**Comment by legacy3** [comment]
yeah no problem, thanks for the lib mate :^)

**Pull request merged**
