### PR TITLE
Feature: Promise Progress Notifications

### PR DESCRIPTION
**Pull request by crazyscience**
It uses `deferred.notify()` to report upload/download progress on the `request` module. Spent the bigger part of 3 hours trying to get tests to pass, but I couldn't for the life of me get it to work. Need to add this code into the request module mock:
```
var  bogusRequestModuleObject = function() {};
bogusRequestModuleObject.prototype.on = function(e, cb) {/* Fake listener registration */}; // eslint-disable-line
return new bogusRequestModuleObject();
```

### CODE REVIEW

**Comment by crazyscience** [comment]
@yakovkhalinsky please advise

**Comment by crazyscience** [comment]
Figured it out. I forgot to implement method chaining. #amateurHour

**Comment by yakovkhalinsky** [comment]
Nice work again @crazyscience 

Merging

**Comment by yakovkhalinsky** [comment]
@crazyscience changes from your last 2 PR's are now published to npm for v0.9.12 👍

**Comment by crazyscience** [comment]
:+1: woo!

**Pull request merged**
