### PR TITLE
timeout arg for file actions

### PR DESCRIPTION
**Pull request by realhidden**
In some cases the b2 servers just wait forever to respond, or the upload is stuck for some reason.

By passing a timeout value you can at least get a reject, and retry the upload. The timeout directly goes into Axios, and is in ms.

### CODE REVIEW

**Comment by cbess** [comment]
Looks good to me as well.

**Comment by Amit-A** [comment]
> Code looks good to me, but I don't see a test for the actual timeout logic. (just updates for the existing tests)

@odensc it looks like the timeout parameter is just being passed on to axios - does it really need testing?

**Comment by odensc** [comment]
@Amit-A True, missed that on first pass. Still would like a mention in the readme though.

**Comment by Amit-A** [comment]
Why not just take an `axios` object parameter that we `Object.assign({}, axios, options)`? This way we can add any axios option (not just timeout).

**Comment by Amit-A** [comment]
> Why not just take an `axios` object parameter that we `Object.assign({}, axios, options)`? This way we can add any axios option (not just timeout).

Just implemented this in #62

**Comment by Amit-A** [comment]
#62 merged: enables timeouts (and any other axios feature) at the request level.

**Pull request closed without merging**
