### PR TITLE
removed vulnerability with axios dependency  update

### PR DESCRIPTION
**Pull request by ps73**
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - [https://github.com/advisories/GHSA-wf5p-g6vw-rhxx](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)

### CODE REVIEW

**Comment by headlessme** [comment]
@yakovkhalinsky could you merge this PR to resolve the axis vulnerability?

**Comment by headlessme** [comment]
@yakovkhalinsky thanks for the quick resolution here! Could you also publish the latest to NPM?

**Comment by yakovkhalinsky** [comment]
@headlessme might take me a few days, I'm on holday at the moment :)

I'll have to set everything up to help with publishing to npm, it's a been a while since I've been involved directly with this repo, regardless I promise to get this done soon 👍

**Comment by headlessme** [comment]
Thanks! Have a nice holiday 🏝️

**Comment by jracabado** [comment]
@yakovkhalinsky sorry I had not seen this thread, I opened an issue related to this CVE: https://github.com/yakovkhalinsky/backblaze-b2/issues/133

**Comment by ps73** [comment]
@yakovkhalinsky Is there any eta when this will be released to npm?

**Pull request merged**
