### PR TITLE
Update library to support latest changes

### PR DESCRIPTION
**Pull request by cbess**
Refactor as needed and remove unneeded deps. Update to use B2 `v2` API. Use ES6 syntax.

### CODE REVIEW

**Comment by cbess** [comment]
All unit tests pass.

**Comment by yakovkhalinsky** [comment]
@cbess looks good, does this supercede the double hash PR?

**Comment by yakovkhalinsky** [comment]
Was thinking we could revise the Node.js versions that we test this against.

Happy to limit to 8, 10 and 11 in the travis.yml.

What do you think @cbess ?

**Comment by cbess** [comment]
> @cbess looks good, does this supercede the double hash PR?

Yes, or we can merge the original PR and I can omit this change. Thoughts?

> Was thinking we could revise the Node.js versions that we test this against.
> 
> Happy to limit to 8, 10 and 11 in the travis.yml.
> 
> What do you think @cbess ?

I agree. Another good package that I use mentioned that this lib requires Node 10:
https://github.com/ItalyPaleAle/SMCloudStore/tree/master/packages/backblaze-b2#system-requirements

Does it?

**Comment by yakovkhalinsky** [comment]
> > @cbess looks good, does this supercede the double hash PR?
> 
> Yes, or we can merge the original PR and I can omit this change. Thoughts?
> 
> > Was thinking we could revise the Node.js versions that we test this against.
> > Happy to limit to 8, 10 and 11 in the travis.yml.
> > What do you think @cbess ?
> 
> I agree. Another good package that I use mentioned that this lib requires Node 10:
> https://github.com/ItalyPaleAle/SMCloudStore/tree/master/packages/backblaze-b2#system-requirements
> 
> Does it?

Sounds good, I think Node.js 10+ is fine since 10 is at LTS 👍

**Comment by cbess** [comment]
@yakovkhalinsky please review
Tests updated: https://travis-ci.org/yakovkhalinsky/backblaze-b2/jobs/480640035

**Comment by cbess** [comment]
@yakovkhalinsky I corrected/updated the milestone to reflect the pkg version:
https://github.com/yakovkhalinsky/backblaze-b2/milestone/15

**Comment by yakovkhalinsky** [comment]
Looks good @cbess you can merge it :+1:

**Comment by odensc** [comment]
@cbess Would you like to publish this to npm or shall I? I think it should be `v2.0.0` because node >=10 is a breaking change.

**Pull request merged**
