### PR TITLE
Add maxRedirects:0 for uploads

### PR DESCRIPTION
**Pull request by realhidden**
Solves the problem of uploading large files, mentioned in #45 . 

Content-Length is also passed to uploadPart the same way as in uploadFile.

### CODE REVIEW

**Comment by Bohica1** [comment]
This would be great to have merged in. Make life simpler

**Comment by burtontanner** [comment]
@realhidden do you know if there is an older version that would also fix this issue? I don't think it is going to get merged any time soon.

**Comment by realhidden** [comment]
You can use my dev branch: https://github.com/realhidden/backblaze-b2/tree/dev

It's easy to install in npm: 

`npm i git://github.com/realhidden/backblaze-b2.git#dev`

Dev branch has all the 3 PRs I sent in.

**Comment by yakovkhalinsky** [comment]
@realhidden if you're interested I can give you access to this repo and add you as a contributor on the npm package.

I don't have much time these days, be a shame to waste the repo and package name 👍

**Comment by realhidden** [comment]
Sure, I would love to.

**Comment by yakovkhalinsky** [comment]
@realhidden have added you as a collaborator, can you please email me your npm username to:
yakov at therocketsurgeon dot com

I'll then add you to the npm package so you can publish versions 👍

**Pull request merged**
